---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  become: true
  gather_facts: false
  become_method: sudo
  become_user: root  

  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  environment:
    - TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION')}}" 
    - TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION')}}"
    - TYPEORM_ENTITIES: "{{ lookup('env', 'TYPEORM_ENTITIES')}}"
    - TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST')}}"
    - TYPEORM_PORT: 5432
    - TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME')}}"
    - TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD')}}"
    - TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE')}}"
    - TYPEORM_MIGRATIONS: "{{ lookup('env', 'TYPEORM_MIGRATIONS')}}"
    - TYPEORM_MIGRATIONS_DIR: "{{ lookup('env', 'TYPEORM_MIGRATIONS_DIR')}}"
  
  pre_tasks:
    - name: "wait 200 seconds for target connection to become reachable/usable."
      wait_for_connection:
        connect_timeout: 200
##############################
    - name: Check for Python
      raw: test -e ansible_python_interpreter
      changed_when: false
      failed_when: false
      register: check_python
##############################

    - name: Install Python
      raw: apt -y update && apt -y install python3
      when: check_python.rc != 0
      

  roles:
    - deploy
